### ISSUE TITLE
Investigate Docker

### ISSUE THREAD

**Issue by SteveWick** [SteveWick/carleton-mail-delivery-robot#1]
- Determine what is necessary to use Docker for builds.
- Create a simple Docker Build method through github.
-- Simple docker build system, even just a hello-world would work

**Comment by SteveWick** [comment]
Created brief write-up of build automation system.
[Build Automation System.pdf](https://github.com/SteveWick/carleton-mail-delivery-robot/files/7213170/Build.Automation.System.pdf)

**Comment by SteveWick** [comment]
Created a basic GitHub action scheme that launches a Dockerfile. 
Action is successful as of b04bf72

**Comment by emnclarke** [comment]
Closing along with write up issue.
