### ISSUE TITLE
Write up about project planning meta

### ISSUE THREAD

**Issue by emnclarke** [SteveWick/carleton-mail-delivery-robot#10]

**Comment by SteveWick** [comment]
Reviewed. Looks good! 👍

**Comment by emnclarke** [comment]
Linking the file. We should probably come up with a better method for this eventually.

[Project Planning and Organization.pdf](https://github.com/SteveWick/carleton-mail-delivery-robot/files/7213650/Project.Planning.and.Organization.pdf)
