### ISSUE TITLE
Run previous year build on robot

### ISSUE THREAD

**Issue by SteveWick** [SteveWick/carleton-mail-delivery-robot#14]
- Get software running on the robot
- Report on the current state of the robot code
- Determine the state of the hardware, if we need to replace any components or order new parts
-

**Comment by SteveWick** [comment]
Pushing this to next week, I want a better understanding of ROS before attempting to run it on the hardware.

**Comment by SteveWick** [comment]
https://github.com/SteveWick/carleton-mail-delivery-robot/wiki/Attempting-to-Run-Previous-Year's-Code

**Comment by pgavigan** [comment]
There is a bring up script specifically for the create 1. See
https://github.com/AutonomyLab/create_robot/blob/melodic/create_bringup/launch/create_1.launch

**Comment by SteveWick** [comment]
Built and ran successfully with Create 1.

**Comment by SteveWick** [comment]
This should be replicated on the create 2.
