### ISSUE TITLE
Review previous year github repo

### ISSUE THREAD

**Issue by emnclarke** [SteveWick/carleton-mail-delivery-robot#5]
Determine the state of each repo and begin exploring what should be re-used or replaced.

**Comment by emnclarke** [comment]
https://github.com/Carleton-Autonomous-Mail-Robot/

**Comment by SteveWick** [comment]
I reviewed the project structure and the web application as part of #9 and #2. We've both read through the repository briefly. I think we should close this issue and any further investigation into the past group's repositories will happen as we look into different components.
